AWSTemplateFormatVersion: '2010-09-09'
Description: 'CezaSavun.ai - IAM Roles for EKS Cluster and Worker Nodes'

# Parameters
Parameters:
  EnvironmentName:
    Description: Environment Name (e.g. dev, prod)
    Type: String
    Default: prod

Resources:
  # EKS Cluster Role
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${EnvironmentName}-EKSClusterRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController

  # EKS Node Role
  EKSNodeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${EnvironmentName}-EKSNodeRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

# Outputs
Outputs:
  EKSClusterRoleArn:
    Description: ARN of the EKS Cluster Role
    Value: !GetAtt EKSClusterRole.Arn
    Export:
      Name: !Sub '${EnvironmentName}-EKSClusterRoleArn'
  
  EKSNodeRoleArn:
    Description: ARN of the EKS Node Role
    Value: !GetAtt EKSNodeRole.Arn
    Export:
      Name: !Sub '${EnvironmentName}-EKSNodeRoleArn'
